[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = "4.5.28"
colored = "3.0.0"
console = "0.15.10"
dirs = "6.0.0"
dotenv = "0.15.0"
notify-rust = "4.11.4"
rusqlite = "0.33.0"
